name: task-app-build-deploy

on:
  push:
    branches:
      - feature/github-actions
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: login to ghcr.io
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_IO_USERNAME }}
          password: ${{ secrets.GHCR_IO_TOKEN }}

      - name: extract docker image metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghrc.io/${{ vars.GHCR_IO_USERNAME }}/task-app

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v4

      - name: build
        uses: docker/bake-action@v7
        with:
          push: false
          set: |
            *.tags=ghrc.io/${{ vars.GHCR_IO_USERNAME }}/task-app:latest
